#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# check prettier
npm run check-format ||
(
  echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
  false;
)

# check ESLint
npm run check-lint ||
(
  echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false; 
)

# check tsconfig standards
npm run check-types ||
(
  echo 'TypeScript Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

npm run build ||
(
  echo '🔨👷🔨 Buidling Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

echo '✅✅✅ You win this time... 🎉🎉🎉'